library_app/urls.py
from django.contrib import admin
from django.urls import path, include

import users
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('books/', views.books_catalog, name='books_catalog'),
    path('control_panel/', views.control_panel, name='control_panel'),
    path('support/', views.support, name='support'),
    path('users/', include('users.urls', namespace='users')),
    path('librarian/book/add/', views.BookCreateView.as_view(), name='book_add'),
    path('librarian/book/<int:pk>/edit/', views.BookUpdateView.as_view(), name='book_edit'),
    path('librarian/loan/add/', views.LoanCreateView.as_view(), name='loan_add'),
    path('loans/', views.LoanListView.as_view(), name='loan_list'),
    path('loans/<int:pk>/edit/', views.LoanUpdateView.as_view(), name='loan_edit'),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_user, name = 'login'),  # users:login
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register, name='register'),
]

core/models/book_copy.py
from django.db import models
from core.models.book_model import Book
from core.models.book_copy_condition_model import BookCopyCondition

def get_next_number():
    max_num = BookCopy.objects.aggregate(models.Max('copy_number'))['copy_number__max']
    return (max_num or 0) + 1

class BookCopy(models.Model):
    bookcopy_id = models.AutoField(primary_key = True)
    copy_number = models.IntegerField(default=get_next_number, unique=True)
    is_available = models.BooleanField()
    book = models.ForeignKey(Book,
        on_delete=models.CASCADE,
        db_column='book_id'
        )
    condition = models.ForeignKey(BookCopyCondition,
        on_delete=models.CASCADE,
        db_column='condition_id'
    )

    def __str__(self):
        return f'Книга: {self.book.title}, экземпляр: {self.copy_number}'

    class Meta():
        db_table = 'bookcopy'

core/models/book_copy_condition_model.py
from django.db import models

class BookCopyCondition(models.Model):
    condition_id = models.AutoField(primary_key = True)
    condition = models.CharField(30, null=True, unique=True)

    def __str__(self):
        return self.condition

    class Meta():
        db_table = 'bookcopycondition'

core/models/book_model.py
from django.db import models

from core.models import Genre
from core.models.publisher_model import Publisher


class Book(models.Model):
    book_id = models.AutoField(primary_key = True)
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=30)
    isbn = models.CharField(max_length=17)
    bbc = models.CharField(max_length=30)
    published_city = models.CharField(max_length=50)
    published_year = models.IntegerField()
    pages = models.IntegerField(default=0)
    image = models.CharField(max_length=50, default= 'book_default.jpg')
    description = models.TextField()
    is_available = models.BooleanField(default=True)

    genre = models.ForeignKey(Genre,
                              on_delete=models.CASCADE,
                              db_column='genre_id')
    publisher = models.ForeignKey(Publisher,
                                  on_delete=models.CASCADE,
                                  db_column='publisher_id'
                                  )

    class Meta():
        db_table = 'book'

    def __str__(self):
        return self.title

core/models/event_model.py
from django.db import models

class Event(models.Model):
    event_id = models.AutoField(primary_key = True)
    image = models.TextField()
    date_time = models.CharField(max_length=40)
    title = models.TextField()

    class Meta():
        db_table = 'event'

    def __str__(self):
        return self.title

core/models/genre_model.py
from django.db import models

class Genre(models.Model):
    genre_id = models.AutoField(primary_key = True)
    genre = models.CharField(max_length=50)

    class Meta():
        db_table='genre'

    def __str__(self):
        return self.genre

core/models/loan_model.py
from datetime import datetime

import django.utils.timezone
from django.db import models

from core.models.book_copy import BookCopy
from core.models.loan_status_model import Status
from core.models.reader_model import Reader


class Loan(models.Model):
    loan_id = models.AutoField(primary_key = True)
    issue_date = models.DateField(verbose_name="Дата выдачи")
    due_date = models.DateField(verbose_name="Дата к которой нужно вернуть книгу")
    return_date = models.DateField(verbose_name="Фактическая дата возврата", blank=True, null=True)
    status = models.ForeignKey(Status,
        on_delete=models.CASCADE,
        db_column='status_id',
        verbose_name="Статус")
    reader = models.ForeignKey(Reader,
        on_delete=models.CASCADE,
        db_column='reader_id',
        verbose_name="Читатель")
    book_copy = models.ForeignKey(BookCopy,
        on_delete=models.CASCADE,
        db_column='bookcopy_id',
        verbose_name="Номер экземпляра")

    class Meta():
        db_table = 'loan'

    def __str__(self):
        return (f'ID: {self.loan_id}, '
                f'книга:  {self.book_copy.book.title}, '
                f'дата выдачи: {self.issue_date}, '
                f'дата ожидаемого возврата: {self.due_date}, '
                f'фактическая дата возврата: {self.return_date if self.return_date else '---'}, '
                f'читатель: {self.reader.first_name} {self.reader.last_name} ')

    def delete(self, *args, **kwargs):
        if self.book_copy:
            self.book_copy.is_available = True
            self.book_copy.save()
        super().delete(*args, **kwargs)

core/models/loan_status_model.py
from django.db import models

class Status(models.Model):
    status_id = models.AutoField(primary_key = True)
    status = models.CharField(max_length=20, unique=True)

    class Meta():
        db_table = 'status'

    def __str__(self):
        return self.status

core/models/publisher_model.py
from django.db import models

class Publisher(models.Model):
    publisher_id = models.AutoField(primary_key = True)
    name = models.CharField(max_length=30)

    class Meta():
        db_table = 'publisher'

    def __str__(self):
        return self.name

core/models/reader_model.py
from django.db import models

class Reader(models.Model):
    reader_id = models.AutoField(primary_key = True)
    ticket_number = models.CharField(max_length=30, unique=True, null=True)
    last_name = models.CharField(max_length=30)
    first_name = models.CharField(max_length=30)
    birth_date = models.DateField()
    address = models.CharField(max_length=100)
    place_of_study = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)

    class Meta():
        db_table = 'reader'

    def __str__(self):
        return self.first_name

core/models/role_model.py
from django.db import models

class Role(models.Model):
    role_id = models.AutoField(primary_key = True)
    role = models.CharField(max_length=20, unique=True, null=True)

    class Meta():
        db_table = 'role'

    def __str__(self):
        return self.role

core/forms.py
from django import forms
from .models import Book, Loan, BookCopy

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['book_copy'].queryset = BookCopy.objects.filter(is_available=True)

            if self.instance.pk:
                self.fields['book_copy'].queryset = BookCopy.objects.filter(
                    models.Q(is_available=True) | models.Q(pk=self.instance.bookcopy.pk)
                )

            self.fields['loan_date'].input_formats = ['%Y-%m-%d', '%d-%m-%Y', '%d.%m.%Y']
            self.fields['return_date'].input_formats = ['%Y-%m-%d', '%d-%m-%Y', '%d.%m.%Y']

core/views.py
from datetime import timedelta

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db import transaction
from django.shortcuts import render
from django.utils import timezone
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView

from core.forms import BookForm, LoanForm
from core.models import Event, Book, Genre, Publisher, Loan


# Create your views here.
def index(request):
    events = Event.objects.all().order_by('pk')

    data = {
        'title': 'Главная страница',
        'events': events
    }
    return render(request, 'index.html', context=data)

def books_catalog(request):
    books = Book.objects.all().order_by('pk')

    # Фильтры
    selected_genre = request.GET.get('genre')
    publisher_id = request.GET.get('publisher')
    max_pages = request.GET.get('max_pages')

    # Поиск
    title_book_find = request.GET.get('books_find')

    if title_book_find:
        books = books_find = books.filter(title__unaccent__icontains=title_book_find)
    elif selected_genre:
        books = books.filter(genre_id=selected_genre)
    elif publisher_id:
        books = books.filter(publisher_id=publisher_id)
    elif max_pages:
        books = books.filter(pages__lte=max_pages)

    context = {
        'books': books,
        'genres': Genre.objects.all(),
        'publishers': Publisher.objects.all(),
    }
    return render(request, 'books_catalog.html', context)

@login_required
def control_panel(request):


    return render(request, 'control_panel.html', {'title': 'Панель управления'})

def support(request):
    ...


class LibrarianBaseMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

class BookCreateView(LibrarianBaseMixin, CreateView):
    model = Book
    form_class = BookForm
    template_name = 'librarian/book_form.html'
    success_url = '/books/'

class BookUpdateView(LibrarianBaseMixin, UpdateView):
    model = Book
    form_class = BookForm
    template_name = 'librarian/book_form.html'
    success_url = '/books/'

class LoanCreateView(LibrarianBaseMixin, CreateView):
    model = Loan
    form_class = LoanForm
    template_name = 'librarian/loan_form.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        with transaction.atomic():
            loan = form.save(commit=False)

            if not loan.issue_date:
                loan.issue_date = timezone.now().date()

            if not loan.due_date:
                loan.due_date = loan.issue_date + timedelta(days=14)

            if loan.status.status == 'Завершен':
                loan.book_copy.is_available = True
                if not loan.return_date:
                    loan.return_date = timezone.now().date()
            else:
                loan.book_copy.is_available = False

            loan.book_copy.save()

            loan.save()

            self.object = loan
            from django.http import HttpResponseRedirect
            return HttpResponseRedirect(self.get_success_url())

class LoanListView(ListView):
    model = Loan
    template_name = 'librarian/loan_list_form.html'
    context_object_name = 'loans'

class LoanUpdateView(UpdateView):
    model = Loan
    form_class = LoanForm
    template_name = 'librarian/loan_edit_form.html'
    success_url = reverse_lazy('loan_list')

    def form_valid(self, form):
        loan = form.save(commit=False)

        if loan.status.status == 'Завершён':
            loan.book_copy.is_available = True
            loan.book_copy.save()

            if not loan.return_date:
                from django.utils import timezone
                loan.return_date = timezone.now().date()
        else:
            loan.book_copy.is_available = False
            loan.book_copy.save()

        loan.save()

        return super().form_valid(form)

core/templates/base.html
<!doctype html>
<html lang="en">
<head>
     {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
<header class="base-header">
    <div class="header_wrapper">
        <div class="logo">
            <a href="{% url 'index' %}">
                <h2>LOGO</h2>
            </a>
        </div>
        <nav class="base-header-nav">
            <a href="{% url 'books_catalog' %}">Книги</a>
            <a href="{% url 'support' %}">Поддержка</a>
            {% if user.is_staff %}
                <a href="{% url 'control_panel' %}">Панель управления</a>
            {% endif %}
        </nav>
        <div class="find-area-box">
            <form action="{% url 'books_catalog' %}" method="get" class="search-form">
                <input type="text" class="find-area-input" placeholder="Поиск книг по каталогу"
                name="books_find">
                <input type="submit"
                       value=""
                       class="find_sumbit"
                       style="background-image: url({% static 'images/search.svg' %})">
            </form>


         </div>
        <div class="login_wrapper">
            {% if user.is_authenticated %}
                <p class="authorized_username">{{ user.username }}</p>
            <p>|</p>
                <a href="{% url 'users:logout' %}" class="logout_link">Выйти</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="login_link">Войти</a>
                <p>|</p>
                <a href="{% url 'users:register' %}" class="register_link">Регистрация</a>
            {% endif %}
        </div>
    </div>
</header>

 {% block content %}{% endblock %}

<footer class="base-footer">
    <ul class="footer-menu">
        <li class="copy-footer-menu-item">
            <a href="/">Поддержка</a>
        </li>
        <li class="copy-footer-menu-item">
            <a href="/">Поддержка</a>
        </li>
        <li class="copy-footer-menu-item">
            <a href="/">Поддержка</a>
        </li>
        <li class="copy-footer-menu-item">
            <a href="/">Поддержка</a>
        </li>
        <li class="copy-footer-menu-item">
            <a href="/">Поддержка</a>
        </li>
    </ul>
</footer>
</body>
</html>

core/templates/books_catalog.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/books_catalog_style.css' %}">
{% endblock %}

{% block content %}

<main class="books_catalog_wrapper">
    <div class="catalog_title"><h1>Каталог</h1></div>

    <div class="books_catalog">
        <section class="filters_section">
    <form method="get" class="filters_form">
        <!-- Жанр -->
        <div class="filter_group">
            <label for="genre">Жанр</label>
            <select name="genre" id="genre">
                <option value="">Все жанры</option>
                {% for g in genres %}
                <option value="{{ g.genre_id }}">{{ g.genre }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Издательство -->
        <div class="filter_group">
            <label for="publisher">Издательство</label>
            <select name="publisher" id="publisher">
                <option value="">Все издательства</option>
                {% for p in publishers %}
                <option value="{{ p.id }}">{{ p.name }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Страницы-->
        <div class="filter_group">
            <label>Страниц до:</label>
            <input type="number" name="max_pages" placeholder="Напр: 500" min="0">
        </div>

        <div class="filter_actions">
            <button type="submit" class="btn_filter">Применить</button>
            <a href="{% url 'books_catalog' %}" class="btn_reset">Сбросить</a>
        </div>
    </form>
</section>

        <div class="books_wrapper">
    {% for book in books %}
    <div class="book_card">
        <div class="book_image">
            <img src="{% static 'images/'|add:book.image %}" alt="{{ book.title }}">
            {% if book.genre %}
                <span class="genre_badge">{{ book.genre.genre }}</span>
            {% endif %}
        </div>

        <div class="book_content">
            <h2 class="book_title">
                {{ book.title }}
                {% if user.is_staff %}
                    | <a href="{% url 'book_edit' book.pk %}" class="button_edit_book">Править</a>
                {% endif %}</h2>
            <p class="book_author">by {{ book.author }}</p>

            <div class="book_meta">
                <p><strong>Издательство:</strong> {{ book.publisher.name }}</p>
                <p><strong>Год:</strong> {{ book.published_year }} г.</p>
                <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            </div>

            <p class="book_description">{{ book.description|truncatewords:15 }}</p>

            <div class="book_footer">
                <span class="bbc_tag">ББК: {{ book.bbc }}</span>
                <span class="pages_count">{{ book.pages }} стр.</span>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
    </div>

</main>

{% endblock %}

core/templates/control_panel.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/control_panel_style.css' %}">
{% endblock %}

{% block content %}
<div class="control_panel">
    <a href="{% url 'book_add' %}">Создание книги</a>
    <a href="{% url 'loan_add' %}">Выдача книги</a>
    <a href="{% url 'loan_list' %}">Просмотр всех выдач</a>
</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
{% endblock %}

{% block content %}
<section class="event-poster">
    <div class="event-poster-title">
        <h2>Мероприятия</h2>
    </div>
        <div class="events-wrapper">
            {% for event in events %}
            <div class="copy-event-item">
                <img src="{% static 'images/'|add:event.image %}" alt="event-image">
                <div class="event-date_time">
                    <p>{{ event.date_time }}</p>
                </div>
                <div class="event-title">
                    <h3>{{ event.title }}</h3>
                </div>
            </div>
            {% endfor %}
        </div>
</section>
{% endblock %}